//항공기 정보
export const airCraftInfo = {
    icao24: 'icao24',
    callsign: 'callsign',
    origin_country: 'origin_country',
    time_position: 'time_position',
    last_contact: 'last_contact',
    longitude: 'longitude',
    latitude: 'latitude',
    baro_altitude: 'baro_altitude',
    on_ground: 'on_ground',
    velocity: 'velocity',
    true_track: 'true_track',
    vertical_rate: 'vertical_rate',
    geo_altitude: 'geo_altitude',
    squawk: 'squawk',
    spi: 'spi',
    position_source: 'position_source',
    category: 'category',
};